# Generated by Django 5.0.3 on 2024-04-19 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='api.league'),
        ),
    ]
