# Generated by Django 5.0.3 on 2024-04-19 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_league_teams_remove_team_players_player_teams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='teams',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='api.team'),
            preserve_default=False,
        ),
    ]
