# Generated by Django 5.0.3 on 2024-04-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_league_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='image',
        ),
        migrations.AddField(
            model_name='league',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
